"""Add short_name to clients and projects

Revision ID: 0ec96ae8b10a
Revises: 94fd5471743c
Create Date: 2026-01-13 11:26:53.530807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec96ae8b10a'
down_revision = '94fd5471743c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
