"""Initial migration

Revision ID: 94fd5471743c
Revises: 
Create Date: 2026-01-13 10:32:28.058043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fd5471743c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('default_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hour_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency IN ('CHF', 'EUR')", name='check_currency'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('idx_clients_active', ['is_active', 'is_archived'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_login_attempts_ip_time', ['ip_address', 'attempted_at'], unique=False)

    op.create_table('work_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_date', ['date'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hourly_rate_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hour_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_active', ['is_active', 'is_archived'], unique=False)
        batch_op.create_index('idx_projects_client', ['client_id'], unique=False)

    op.create_table('time_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('hours > 0 AND MOD(hours * 4, 1) = 0', name='check_hours_increment'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_allocations', schema=None) as batch_op:
        batch_op.create_index('idx_allocations_date', ['date'], unique=False)
        batch_op.create_index('idx_allocations_project', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_allocations', schema=None) as batch_op:
        batch_op.drop_index('idx_allocations_project')
        batch_op.drop_index('idx_allocations_date')

    op.drop_table('time_allocations')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_client')
        batch_op.drop_index('idx_projects_active')

    op.drop_table('projects')
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_date')

    op.drop_table('work_sessions')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_login_attempts_ip_time')

    op.drop_table('login_attempts')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('idx_clients_active')

    op.drop_table('clients')
    # ### end Alembic commands ###
